# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKid4vjija3o26npW7MtOgBDmKWAh3Z_
"""

import numpy as np
import math

a = 6
b = 9.5
theta = 5*math.pi/12
alpha = 7*math.pi/6
beta = 7*math.pi/9

#calculating e
e = (a**2 + b**2 -2*a*b*math.cos(alpha))**0.5

#calculating d
#specifically denominator of d
print(math.sin(2*math.pi - (theta + alpha + beta)))
#it is negative, so quadrilateral not possible