# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WaQBpYlIPCP-k3tp_YYEBINx2iut1fNb
"""

import numpy as np
import matplotlib.pyplot as plt
from sympy.matrices import Matrix

#input points
A=np.array([21,-2])
B=np.array([15,10])
C=np.array([-5,0])
D = np.array([1,-12])

# Finding the which two sides are equal
print("length AB:",np.linalg.norm(A-B))
print("length BC",np.linalg.norm(B-C))
print("length CD",np.linalg.norm(C-D))
print("length DA:",np.linalg.norm(D-A))

#function for line generation
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#generating lines
x_AB = line_gen(A,B)
x_BC = line_gen(B,C)
x_CD = line_gen(C,D)
x_DA = line_gen(D,A)

#center of the rectangle
O = (A+C)/2

#plotting the quadrilateral
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_BC[0,:],x_BC[1,:],label='$BC$')
plt.plot(x_CD[0,:],x_CD[1,:],label='$CD$')
plt.plot(x_DA[0,:],x_DA[1,:],label='$DA$')

#plotting points
plt.plot(A[0], A[1], 'o')
plt.text(A[0] * (1 + 0.03), A[1] * (1 + 0.01) , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(B[0] * (1 + 0.1), B[1] * (1) , 'B')
plt.plot(C[0], C[1], 'o')
plt.text(C[0] * (1 + 0.003), C[1] * (1 + 0.1) , 'C')
plt.plot(D[0],D[1],'o')
plt.text(D[0] * (1 + 0.2), D[1] * (1 + 0.13) , 'D')
plt.plot(O[0], O[1], 'o')
plt.text(O[0] * (1 + 0.03), O[1] * (1 + 0.01) , 'O')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()