# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nfLH-dzhL_iRb52oAzRdCxEkvSgDCibu
"""

import numpy as np
import matplotlib.pyplot as plt

#As alpha is an arbitrary constant where 0 < |alpha| < 1
#Let's consder alpha is 0.6
#Real and imaginary parts of alpha
Re_a = 0.6
Img_a = 0
pole1 = [Re_a,Img_a]
pole2 = [Re_a/(Re_a*Re_a + Img_a*Img_a) , -Img_a/(Re_a*Re_a + Img_a*Img_a)]
zero = [0,0]

theta = np.linspace(0, 2*np.pi, n, endpoint=True)

ax = plt.subplot(111, aspect='equal')

plt.plot(np.sin(theta), np.cos(theta) , 'k-' , label = "Unit Circle: $|z| = 1$")
plt.plot([pole1[0] , pole2[0]] , [pole1[1],pole2[1]] , 'rx' , label = "Poles of $X(z)$")
plt.plot(zero[0] , zero[1] , 'ro' , label = "Zeroes of $X(z)$")
plt.title("Pole-Zero Plot considering alpha = 0.6")
plt.grid(True)
plt.legend()
plt.show()