# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12LrYat1J1ddNB2kTvDyDL_fRF-083VJe
"""

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
fig, ax = plt.subplots()
# setting the x - coordinates
x = np.arange(-20, 30, 0.1)
# setting the corresponding y - coordinates
y = 1/x

label = plt.axvline(x=0,label="Re{s}=0",color='red')
'''x1= 2
y1 = np.arange(-20, 30, 0.1)'''
# plotting the points

'''plt.plot(x1,y1)'''
plt.xlim(-5,10)
plt.annotate("0", (0+0.02, 0+0.01))

line1 = 0 # vertical x = 0
line2 = 50 # vertical x = 50
pole, = plt.plot(0,0, 'ro',label = 'pole',color='green')
ax.axvspan(line1, line2, alpha=.5, color='blue')
patches = mpatches.Patch(color="blue", label="ROC")
plt.legend(handles=[patches,label,pole], loc = 'upper right')
plt.xlabel("Re{s}")
plt.ylabel("jW")
# function to show the plot
plt.grid()
plt.show()
#There are two complex poles

fig, ax = plt.subplots()
# setting the x - coordinates
x = np.arange(-20, 30, 0.1)
# setting the corresponding y - coordinates
y = 1/(3+x)

label = plt.axvline(x=0,label="Re{s}=0",color='red')
'''x1= 2
y1 = np.arange(-20, 30, 0.1)'''
# plotting the points

'''plt.plot(x1,y1)'''
plt.xlim(-5,5)
plt.annotate("-3", (-3+0.02, 0+0.01))
line1 = -3 # vertical x = 3
line2 = 50 # vertical x = 5
pole, = plt.plot(-3,0, 'ro',label = 'pole',color='green')

ax.axvspan(line1, line2, alpha=.5, color='blue')
patches = mpatches.Patch(color="blue", label="ROC")
plt.legend(handles=[patches,label,pole], loc = 'upper right')
plt.xlabel("Re{s}")
plt.ylabel("jW")
# function to show the plot
plt.grid()
plt.show()
#There are two complex poles