# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ci1cEjNpICsg9APzktGZ0WXNGmJQzHM
"""

import numpy as np

A = np.array([[3, -2], [4, -2]])
I = np.array([[1,0], [0,1]])

#Finding inverse of A
Ainv = np.linalg.inv(A)

#As AA +2I = kA ==> (AA +2I)Ainv = kI
(A@A +2*I)@ainv

#So k = 1